name: Documentation Build Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev] || (pip install -e . && pip install -r requirements-dev.txt)
        
    - name: Verify Sphinx installation
      run: |
        python -m sphinx --version
        
    - name: Build documentation
      run: |
        cd docs
        python -m sphinx -b html source build -W
        
    - name: Check documentation links
      run: |
        cd docs
        python -m sphinx -b linkcheck source build
        
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation-html
        path: docs/build/
        retention-days: 30
